eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8086

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: users-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digital-media
        registration:
          keycloak:
            client-id: dh-media
            client-secret: jcxRW1Zid1fG3z9XYaaob15f8Z87huJm
            scope: openid
            redirect_uri: http://localhost:8095
  data:
    mongodb:
      host: localhost
      port: 27017
      password: admin
      username: root
      authentication-database: admin
      database: moviesdb
  main:
    allow-circular-references: true
