spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/digital-media
            authorization-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/auth
            token-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/token
            user-info-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/userinfos
            jwk-set-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/certs
        registration:
          api-gateway:
            scope: openid
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: hfbQoAfKDzcOgRTCkWrvppMYn8eShntN
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:9090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**

        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/api/movies/**

        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/bills/**


server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true