spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/digital-media
        registration:
          api-gateway:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: jcxRW1Zid1fG3z9XYaaob15f8Z87huJm
            authorization-grant-type: authorization_code
            redirect_uri: http://localhost:9090
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2

        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/bills/**
          filters:
            - StripPrefix=2

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true