spring:
  application:
    name: movies-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digital-media
        registration:
          keycloak:
            client-id: dh-media
            client-secret: jcxRW1Zid1fG3z9XYaaob15f8Z87huJm
            scope: openid
            redirect_uri: http://localhost:8095

#app:
#  cors:
#    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
server:
  port: 8097

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true